routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','GeneralController@welcome')->name('/');
// Route::post('/setcookie','GeneralController@setcookie')->name('setcookie');
// Route::get('/cookies-policy','GeneralController@cookiesPolicy')->name('cookies-policy');
//Routes For pages

// Route::get('/kisisellestirilmis-beslenme', 'GeneralController@kisisellestirilmis_beslenme')->name('kisisellestirilmis-beslenme');
// Route::get('/bagisiklik', 'GeneralController@bagisiklik')->name('bagisiklik');
// Route::get('/mikrobiyom-testleri', 'GeneralController@mikrobiyom_testleri')->name('mikrobiyom_testleri');
// Route::get('/kilo-kontrolu', 'GeneralController@kilo_kontrolu')->name('kilo-kontrolu');
// Route::get('/bagirsak-hastaliklari', 'GeneralController@bagirsak_hastaliklari')->name('bagirsak-hastaliklari');
// Route::get('/ibs', 'GeneralController@ibs')->name('ibs');
// Route::get('/gida-hassasiyeti', 'GeneralController@colyak')->name('colyak-hastalıgı');
// Route::get('/mikrobiyom-diyeti', 'GeneralController@mikrobiyomDiyeti')->name('mikrobiyom-diyeti');
// Route::get('/actifit', 'GeneralController@actifit')->name('actifit');
// Route::get('/investor ', 'GeneralController@yatirimci')->name('yatirimci');

Route::get('/mesafeli-satis-sozlesmesi', 'GeneralController@mesafeliSatisSozlesmesi')->name('mesafeli-satis-sozlesmesi');

Route::get('/on-bilgilendirme-formu', 'GeneralController@onBilgilendirmeFormu')->name('on-bilgilendirme-formu');

Route::get('/aydinlatma-formu', 'GeneralController@aydinlatmaFormu')->name('aydinlatma-formu');

// Route::get('/tesekkurler/{traking}', 'GeneralController@tesekkurler')->name('tesekkurler');

// Route::get('/uyelik-sozlesmesi', 'GeneralController@uyelikSozlesmesi')->name('uyelik-sozlesmesi');

// Route::get('/gizlilik-politikasi', 'GeneralController@gizlilikPolitikasi')->name('gizlilik-politikasi');

// Route::get('hakkimizda', 'GeneralController@hakkimizda')->name('hakkimizda');

// Route::get('/mikrobiyom', 'GeneralController@mikrobiyom')->name('mikrobiyom');

// Route::get('/urunlerimiz', 'GeneralController@mikrobiyom_analizi')->name('mikrobiyom-analizi');

// Route::get('bilim', 'GeneralController@bilim')->name('bilim');

// Route::get('enbiosis-test', 'GeneralController@enbiosisTest')->name('enbiosis-test');

// Route::get('sss', 'GeneralController@sss')->name('sss');

// Route::get('iletisim', 'GeneralController@iletisim')->name('iletisim');

// Route::post('iletisim', 'GeneralController@sendMail')->name('send_iletisim');

// newsletter 
// Route::post('newsletter', 'GeneralController@newsletter')->name('newsletter');

//Prof. Dr. Hakan Alagözlü cv

// Route::get('prof-dr-hakan-alagozlu', 'GeneralController@profDrHakanAlagozlu')->name('prof-dr-hakan-alagozlu');

// //Prof. Dr. Hakan Alagözlü cv

// Route::get('prof-dr-tarkan-karakan', 'GeneralController@profDrTarkanKarakan')->name('prof-dr-tarkan-karakan');

// //Prof. Dr. Halil Coşkun

// Route::get('prof-dr-halil-coskun', 'GeneralController@profDrHalilCoskun')->name('prof-dr-halil-coskun');

// //Dr. Özkan Ufuk Nalbantoğlu

// Route::get('dr-ozkan-ufuk-nalbantoglu', 'GeneralController@drOzkanUfukNalbantoglu')->name('dr-ozkan-ufuk-nalbantoglu');

// //Doç. Dr. Aycan Gündoğdu

// Route::get('doc-dr-aycan-gundogdu', 'GeneralController@docDrAycanGundogdu')->name('doc-dr-aycan-gundogdu');

// //Doç. Dr. Aycan Gündoğdu

// Route::get('ceo-omer-ozkan', 'GeneralController@ceoOmerOzkan')->name('ceo-omer-ozkan');

/*
|--------------------------------------------------------------------------
| Lang Route
|--------------------------------------------------------------------------
*/
Route::get('locale/{locale}', 'GeneralController@locale')->name('lang');

// For Ajax Request For updata and remove items from cart
Route::post('update-cart', 'ShopController@updateCartProduct');

Route::post('installment', 'ShopController@installment');
// Show CheckOut Form
Route::get('checkout', 'CheckoutController@index')->name('checkout');
// Get County based in City
Route::post('getCounty', 'ShopController@getCounty')->name('getCounty');
// get instalments table
Route::post('instalmentsTable', 'GeneralController@instalmentsTable')->name('instalmentsTable');
// Check for Coupon  Form
Route::post('checkForCoupon', 'ShopController@checkForCoupon')->name('checkForCoupon');
// Remove Coupon From Payment form
Route::post('removeCouponFromPaymentForm', 'ShopController@removeCouponFromPaymentForm')->name('removeCouponFromPaymentForm');

// Show CheckOut For prodduct
Route::get('checkout/{slug}', 'ShopController@showCheckOut')->name('checkout.product');
// Submit CheckOut For prodduct
Route::post('checkout/{slug}', 'ShopController@CheckOut')->name('checkout.product.submit');


// Route For get POST Requset from bank api for results
Route::post('checkout-result/{slug}', 'ShopController@CheckOutResult')->name('checkout.result.p');

Route::get('/tesekkurler/{slug}/{traking}', 'GeneralController@tesekkurler')->name('tesekkurler');

//campaign pages
// Show campaign CheckOut Page
// Route::get('kampanya', 'CheckoutController@campaign')->name('Campaign');
// // // Show campaign CheckOut Page
// Route::get('kampanya/{campaignCode}', 'CheckoutController@campaignIndex')->name('checkout.Campaign');
// // // Show campaign CheckOut form
// Route::get('checkout/{campaignCode}/{slug}', 'ShopCampaignController@index')->name('checkout.Campaign.index');

// // updaate kit quantity in campaign 
// Route::post('campaign-update-cart/{campaignCode}', 'ShopCampaignController@updateQuantity')->name('checkout.Campaign.updatecart');

// // get instalments table
// Route::post('campaign-instalments-table/{campaignCode}', 'ShopCampaignController@campaignInstalmentsTable')->name('checkout.campaign.instalmentsTable');

// // Submit CheckOut campaign Form
// Route::post('checkout/{campaignCode}/{slug}', 'ShopCampaignController@CheckOut')->name('checkout.campaign.submit');

// // Submit CheckOut result campaign Form
// Route::post('checkout-result/{campaignCode}/{slug}', 'ShopCampaignController@CheckOutResult')->name('checkout.campaign.result');
/*
|--------------------------------------------------------------------------
|   Auth Routes For User
|--------------------------------------------------------------------------
*/
Auth::routes(['verify' => true, 'register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

// Register kit Routes
Route::get('register-kit', 'Auth\UserRegisterKitController@showRegisterKitForm')->name('register-kit.form');
Route::post('register-kit', 'Auth\UserRegisterKitController@RegisterKit')->name('register-kit');

Route::get('register-kit-user', 'Auth\UserRegisterKitController@showRegisterKitWithUserForm')->name('register-kit-user.form');
Route::post('register-kit-user', 'Auth\UserRegisterKitController@registerKitWithUser')->name('register-kit-user');
Route::post('login-kit-user', 'Auth\UserRegisterKitController@LoginUserAfterKitCodeMatch')->name('login-kit-user');


/*
|--------------------------------------------------------------------------
| Login and Loguot Routes For Admin
|--------------------------------------------------------------------------
*/
Route::prefix('admin')->group(function() {

    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    // Route::get('/', 'AdminController@index')->name('admin.index');
}) ;

/*
|--------------------------------------------------------------------------
| Login and Loguot Routes For dietitian
|--------------------------------------------------------------------------
*/
Route::prefix('dietitian')->group(function() {

    Route::get('/login','Auth\DietitianLoginController@showLoginForm')->name('dietitian.login');
    Route::post('/login', 'Auth\DietitianLoginController@login')->name('dietitian.login.submit');
    Route::post('logout/', 'Auth\DietitianLoginController@logout')->name('dietitian.logout');
    // Route::get('/', 'DietitianController@index')->name('dietitian.index');
}) ;



/*
|--------------------------------------------------------------------------
| ADMIN Route
|--------------------------------------------------------------------------
*/
Route::get('/admin','AdminController@index')->middleware(['auth:admin', 'admin'])->name('admin.index');
Route::patch('/admin/profile','AdminController@updateProfile')->name('admin.updateProfile');
// operation admin
Route::group(['prefix' => 'operation',  'middleware' => ['auth:admin', 'admin', 'op-admin'], 'as' => 'operation.'], function()
{
    Route::get('/','OperationAdminController@indexRoute')->name('index');
    Route::get('/profile','AdminController@OperationAdminProfile')->name('profile');

    // Admin Orders MAnagement Section Routes
    Route::post('/orders/query', 'OperationAdminController@search')->name('orders.search');
    Route::get('/orders/export', 'OperationAdminController@export')->name('orders.export');
    Route::patch('/kit/{kit}', 'OperationAdminController@updateKit')->name('kit.update');
    Route::post('/kit/delever', 'OperationAdminController@kitDeleverToUser')->name('kit.delever');
    Route::post('/kit/received', 'OperationAdminController@kitReceived')->name('kit.received');
    Route::post('/kit/sent', 'OperationAdminController@kitSentToLab')->name('kit.sent');

    Route::get('/kits', 'OperationAdminController@Kit')->name('kit');
    Route::post('/kits/query', 'OperationAdminController@Kitsearch')->name('kit.search');

    /*

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Product extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'price', 'discount_price', 'slug', 'description', 'stok', 'number_of_kit'
    ];

    public function photo()
    {
        return $this->morphOne('App\Photo', 'imageable');
    }

    public function admin()
    {
        return $this->belongsTo('App\Admin');
    }

    public function OrderDetail()
    {
        return $this->hasMany('App\OrderDetail');
    }

    public function getDiscountAttribute()
    {
        if($this->discount_price == NULL)
            return '<td class="text-danger"> Do Not Have A Discount </td>';
        else
            return '<td class="text-success">' . (double) ( ( ( 100 - $this->discount_price ) * $this->price ) / 100 ) . ' / ' . $this->discount_price .  ' % </td>'; 

    }
}

resources/views/campaignCheckout.blade.php
@extends('layouts.public')
@section('subpageMenu','topmenu--subpage')
@section('pageTitle', __('pages/checkout.page_title'))
@section('pageDescription', __('pages/checkout.page_description'))
@section('metaTag')
<meta name="robots" content="noindex">
@endsection
@section('styles')
	<style>
		.strike {
			color: #514689 !important;
		}
	</style>
@endsection
@section('content')
<section class="subpage-header subpage-header--checkout">
	<div class="container">
		<div class="row">
			<div class="subpage-header__content">
				<h1 class="subpage-header__title">{{__('pages/checkout.header_title')}}</h1>
				<div class="subpage-header__seperator"></div>
				<div class="subpage-header__breadcrumb">
					<nav aria-label="breadcrumb">
						<ol itemscope itemtype="https://schema.org/BreadcrumbList"
						class="breadcrumb no-bg-color text-light">
							<li itemprop="itemListElement" itemscope
							itemtype="https://schema.org/ListItem"
							class="breadcrumb-item">
								<a itemprop="item"
								style="color:#007bff"
								href="{{ route('/')}}">
								<span itemprop="name">{{__('pages/checkout.breadcrumb.0')}}</span>
								</a>
								<meta itemprop="position" content="1"/>
							</li>
							<li itemprop="itemListElement" itemscope
							itemtype="https://schema.org/ListItem"
							class="breadcrumb-item te">
								<a itemprop="item" 
								style="color:#007bff"
								href="{{ route('checkout')}}">
									<span itemprop="name">{{__('pages/checkout.breadcrumb.1')}}</span>
								</a>
								<meta itemprop="position" content="2"/>
							</li>
							<li itemprop="itemListElement" itemscope
							itemtype="https://schema.org/ListItem"
							class="breadcrumb-item active te">
								<a itemprop="item" 
								style="color:#6c757d"
								href="{{ route('checkout.Campaign', strtolower($coupon->code))}}">
									<span itemprop="name">{{ucwords($coupon->code)}}</span>
								</a>
								<meta itemprop="position" content="2"/>
							</li>
						</ol>
						{{-- <ol class="breadcrumb no-bg-color text-light">
						  <li class="breadcrumb-item"><a href="{{ route('/')}}">{{__('pages/checkout.breadcrumb.0')}}</a></li>
						  <li class="breadcrumb-item active" aria-current="page">{{__('pages/checkout.breadcrumb.1')}}</li>
						</ol> --}}
					</nav>
				</div>
			</div>
		</div>
	</div>
</section>
<section class=" buy__first pricing py-5" style="margin: 0">
	<div class="container">
		<div class="row buy__row justify-content-center">
			<div class="text-center col-12 mb-5">
				<h2 class="triple-box__title" style="color:#e8957e">{{ucwords($coupon->code)}} Kapmanyasına katılarak %{{$coupon->discount}} indirimi uygulanacak</h2>
			</div>
		</div>
		<div class="row buy__row justify-content-center">
			@foreach ($products as $product)
			<div class="col-lg-6 mt-lg-0 mt-3">
				<div class="card mb-5 mb-lg-0" style="height: 100%;background-color: rgba(255, 255, 255, 0.9);">
					<div class="card-body">
						<h6 class="card-price text-center">{{$product->name}}</h6>
						<h6 class="card-price text-center">
							<strike class="">{{$product->price + 500}} TL</strike>
						</h6>
						<h6 class="card-price text-center">
							<strike class="mr-3">{{$product->price}} TL</strike>
							{{ round ( (double) ( ( ( 100 - $coupon->discount ) * $product->price ) / 100 ), 2)}} TL
						</h6>
						<hr>
						<div class="my-1">
							@if ($product->slug == 'mikrobiyom-saglik-paketi')
								<ul class="fa-ul list-style-type text-center" style="list-style-type: none;">
									<li><b>Mikrobiyom Analizi</b></li>
									<li><b>Kişiselleştirilmiş Beslenme Rehberi</b></li>
								</ul>
								<div class="text-center mt-5 mt-checkout mb-3">
									<img src="{{url('/new/img/saglik_kit.webp')}}" alt="" class="mb-2"> <br>
									<a class="link-btn link-btn--orange" href="{{route('checkout.Campaign.index', [$coupon->code, $product->slug])}}">SATIN AL</a>
								</div>
							@elseif($product->slug == 'mikrobiyom-saglik-paketi-premium')
								<ul class="fa-ul list-style-type text-center" style="list-style-type: none;">
									<li><b>Mikrobiyom Analizi</b></li>
									<li><b>Kişiselleştirilmiş Beslenme Rehberi</b></li>
									<li><b>Diyetisyen desteği</b></li>
								</ul>
								<div class="text-center mt-5 mb-3">
									<img src="{{url('/new/img/saglik_kit_premium.webp')}}" alt="" class="mb-2"> <br>
									<a class="link-btn link-btn--orange" href="{{route('checkout.Campaign.index', [$coupon->code, $product->slug])}}">SATIN AL</a>
								</div>
							@endif
						</div>
					</div>
				</div>
			</div>
			@endforeach
		</div>
	</div>
</section>
<section class="triple-box" style="margin: 60px 0 0 0;">
	<div class="container">
		<div class="row">
			<div class="col-12 triple-box__box text-center pb-3">
				<span><i>Bağırsaklarında trilyonlarca bakteri var, bu bakterileri keşfederek sorunların kaynağına inmek ve kişiselleştirilmiş sağlık yolculuğuna adım atmak artık senin elinde!</i></span>
			</div>
			<div class="col-md-4 triple-box__box text-center">
				<img src="{{url('/')}}/new/img/triple-icon1.webp" />
				<span>{{__('pages/urunlerimiz.box_item_1')}}</span>
				<p> Bağırsak bakteri ekosisteminin analizi</p>
			</div>
			<div class="col-md-4 triple-box__box text-center">
				<img src="{{url('/')}}/new/img/triple-icon2.webp" />
				<span>{{__('pages/urunlerimiz.box_item_2')}}</span>
				<p> Vücudunun ihtiyaç duyduğu besinlerin raporu</p>
			</div>
			<div class="col-md-4 triple-box__box text-center">
				<img src="{{url('/')}}/new/img/triple-icon3.webp" />
				<span>{{__('pages/urunlerimiz.box_item_3')}}</span>
				<p> 6 haftalık diyetisyen takibi </p>
			</div>
		</div>
	</div>
</section>
@endsection

@section('scripts')
@endsection

resources/views/checkout.blade.php
@extends('layouts.public')
@section('subpageMenu','topmenu--subpage')
@section('pageTitle', __('pages/checkout.page_title'))
@section('pageDescription', __('pages/checkout.page_description'))
@section('metaTag')<meta name="robots" content="noindex">@endsection
@section('styles')
<style>
@media screen and (max-width: 768px)
{.buy__row {flex-direction: initial !important;}}
</style>
@endsection
@section('content')
<section class="subpage-header subpage-header--checkout" 
	@if (app()->getlocale() == 'en') style ="background-image: url({{url('/')}}/new/img/checkout-mobile.webp);"@endif>
	<div class="container">
		<div class="row">
			<div class="subpage-header__content">
				<h1 class="subpage-header__title">{{__('pages/checkout.header_title')}}</h1>
				<div class="subpage-header__seperator"></div>
				<div class="subpage-header__breadcrumb">
					<nav aria-label="breadcrumb">
						<ol itemscope itemtype="https://schema.org/BreadcrumbList"
						class="breadcrumb no-bg-color text-light">
							<li itemprop="itemListElement" itemscope
							itemtype="https://schema.org/ListItem"
							class="breadcrumb-item">
								<a itemprop="item"
								style="color:#007bff"
								href="{{ route('/')}}">
								<span itemprop="name">{{__('pages/checkout.breadcrumb.0')}}</span>
								</a>
								<meta itemprop="position" content="1"/>
							</li>
							<li itemprop="itemListElement" itemscope
							itemtype="https://schema.org/ListItem"
							class="breadcrumb-item active te">
								<a itemprop="item" 
								style="color:#6c757d"
								href="{{ route('checkout')}}">
									<span itemprop="name">{{__('pages/checkout.breadcrumb.1')}}</span>
								</a>
								<meta itemprop="position" content="2"/>
							</li>
						</ol>
						{{-- <ol class="breadcrumb no-bg-color text-light">
						  <li class="breadcrumb-item"><a href="{{ route('/')}}">{{__('pages/checkout.breadcrumb.0')}}</a></li>
						  <li class="breadcrumb-item active" aria-current="page">{{__('pages/checkout.breadcrumb.1')}}</li>
						</ol> --}}
					</nav>
				</div>
			</div>
		</div>
	</div>
</section>
<section class=" buy__first pricing py-5" style="margin: 0;height:auto !important">
	<div class="container">
		<div class="row buy__row justify-content-center">
			@foreach ($products as $product)
				<div class="col-lg-6 {{$loop->index != 2 ? 'mt-lg-0' : ''}} mt-3">
					<div class="card mb-5 mb-lg-0" style="height: 100%;background-color: rgba(255, 255, 255, 0.9);">
						<div class="card-body">
							
							<h6 class="card-price text-center">{!!__('pages/checkout.'.$product->slug)!!}</h6>
							<h6 class="card-price text-center">
								{{-- <strike class="mr-2">{{$product->price + 500}} $</strike> --}}
								{{$product->price}} $
							</h6>
							<hr>
							<div class="my-1">
								@if ($product->slug == 'mikrobiyom-saglik-paketi')
									<ul class="fa-ul list-style-none text-center" style="list-style-type: none;">
										<li><b>تحليل بكتيريا الأمعاء</b></li>
										<li><b>دليل التغذية المخصص</b></li>
										{{-- <li><b>Kişiselleştirilmiş Beslenme Rehberi </b>ile sana en uygun besinleri öğren</li> --}}
										{{-- <li class="text-muted"><span class="fa-li"><i class="fas fa-times"></i></span>Monthly Status Reports</li> --}}
									</ul>
									<div class="text-center mt-5 mt-checkout mb-3">
										<img src="{{url('/new/img/saglik_kit.webp')}}" alt="" class="mb-2"> <br>
										<a class="link-btn link-btn--orange" href="{{route('checkout.product', $product->slug)}}">
											{{mb_strtoupper(__('pages/checkout.breadcrumb.1'))}}
										</a>
									</div>
								@elseif($product->slug == 'mikrobiyom-saglik-paketi-premium')
									<ul class="fa-ul list-style-type text-center" style="list-style-type: none;">
										<li><b>تحليل بكتيريا الأمعاء</b></li>
										<li><b>دليل التغذية المخصص</b></li>
										<li><b>دعم أخصائي التغذية</b></li>
									</ul>
									<div class="text-center mt-5 mb-3">
										<img src="{{url('/new/img/saglik_kit_premium.webp')}}" alt="" class="mb-2"> <br>
										<a class="link-btn link-btn--orange" href="{{route('checkout.product', $product->slug)}}">
											{{mb_strtoupper(__('pages/checkout.breadcrumb.1'))}}
										</a>
									</div>
								{{-- @elseif($product->slug == 'takipli-premium-mikrobiyom-saglik-paketi')
									<ul class="fa-ul list-style-none text-center" style="list-style-type: none;">
										<li><b>2’li Mikrobiyom Analizi</b></li>
										<li><b>2’li Kişiselleştirilmiş Beslenme Rehberi</b></li>
										<li><b>12 Haftalık Diyetisyen Desteği</b></li>
									</ul>
									<div class="text-center">
										<small>
											*ENBIOSIS ile başladığın yolculukta bağırsak bakterilerindeki iyileşmeye bağlı olarak
											vücudunun ihtiyaç duyduğu besinler de değişir, hayatın boyunca kendine daha iyi bakabilmen
											için takipli paketi öneriyoruz.
											</small> <br>
										<img src="{{url('/new/img/saglik_kit_takipli.webp')}}" alt="" class="mb-4"> <br>
										<a class="link-btn link-btn--orange" href="{{route('checkout.product', $product->slug)}}">
											{{mb_strtoupper(__('pages/checkout.breadcrumb.1'))}}
										</a>
									</div> --}}
								@endif
							</div>
						</div>
					</div>
				</div>
			@endforeach
		</div>
	</div>
</section>
{{-- <section class="triple-box" style="margin: 60px 0 0 0;">
	<div class="container">
		<div class="row">
			<div class="col-12 triple-box__box text-center pb-3">
				<span><i>{{__('pages/checkout.desc')}}</i></span>
			</div>
			<div class="col-md-4 triple-box__box text-center">
				<img src="{{url('/')}}/new/img/triple-icon1.webp" />
				<span>{{__('pages/urunlerimiz.box_item_1')}}</span>
				<p>{{__('pages/checkout.box.0')}}</p>
			</div>
			<div class="col-md-4 triple-box__box text-center">
				<img src="{{url('/')}}/new/img/triple-icon2.webp" />
				<span>{{__('pages/urunlerimiz.box_item_2')}}</span>
				<p>{{__('pages/checkout.box.1')}}</p>
			</div>
			<div class="col-md-4 triple-box__box text-center">
				<img src="{{url('/')}}/new/img/triple-icon3.webp" />
				<span>{{__('pages/urunlerimiz.box_item_3')}}</span>
				<p>{{__('pages/checkout.box.2')}}</p>
			</div>
		</div>
	</div>
</section> --}}
@endsection

@section('scripts')
@endsection

resources/views/enbiosis-test.blade.php
@extends('layouts.public')

@section('content')
<section class="header subpage test">
	<div class="container">
        <h1 class="title"> {{__('app.enbiosis_test')}}</h1>
	</div>
</section>
<section class="test-content">

    <div class="container">
		<p class="text">
			{!! __('app.test_1')  !!}
		</p>
	</div>

	
</section>
<section class="features">


	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="f-item">
					<img src="{{url('/')}}/img/f-icon-1.png" />
                    {!! __('app.test_2_1') !!}
				</div>
			</div>
			<div class="col-md-6">
				<div class="f-item">
					<img src="{{url('/')}}/img/f-icon-2.png" />
                    {!! __('app.test_2_2') !!}
				</div>
			</div>
			<div class="col-md-6">
				<div class="f-item">
					<img src="{{url('/')}}/img/f-icon-3.png" />
                    {!! __('app.test_2_3') !!}
				</div>
			</div>
			<div class="col-md-6">
				<div class="f-item">
					<img src="{{url('/')}}/img/f-icon-4.png" />
                    {!! __('app.test_2_4') !!}
				</div>
			</div>
			<div class="col-md-6">
				<div class="f-item">
					<img src="{{url('/')}}/img/f-icon-5.png" />
                    {!! __('app.test_2_5') !!}
				</div>
			</div>
			<div class="col-md-6">
				<div class="f-item">
					<img src="{{url('/')}}/img/f-icon-6.png" />
					{!! __('app.test_2_6') !!}
				</div>
			</div>
		</div>
    </div>
</section>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="row justify-content-center px-4">
    <div class="col">
        <div class="card">
            <div class="card-header">Dashboard</div>

            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif

                You are logged in!
            </div>
        </div>
    </div>
</div>
@endsection