routes/web.php
    Route::resource('surveys', 'AdminSurveyController', ['except' => ['show', 'edit'] ]);

    //Admin Survey Sections Management Section Routes

    // Store a new Lang for Survey Section
    Route::post('{id}/sections/create/lang/{sectionId}', 'AdminSurveySectionsController@storeLang')->name('sections.lang.store');

    // Update Lang for Survey Section
    Route::patch('{id}/sections/update/lang/{sectionId}-{langid}', 'AdminSurveySectionsController@updateLang')->name('sections.lang.update');

    // Delete Lang for Survey Section
    Route::delete('{id}/sections/delete/lang/{sectionid}-{langid}', 'AdminSurveySectionsController@destroyLang')->name('sections.lang.destroy');

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('{id}/sections', 'AdminSurveySectionsController', ['except' => ['show', 'edit'] ]);

    //Admin Survey Sections  questions Management Section Routes

    // Store a new Lang for Survey Section question

    //create view
    Route::get('{survey}/{sections}/questions/create/lang/{questionId}', 'AdminQuestionController@createLang')->name('questions.lang.create');

    // store record
    Route::post('{survey}/{sections}/questions/store/lang/{questionId}', 'AdminQuestionController@storeLang')->name('questions.lang.store');

    // Delete Lang for Survey Section
    Route::delete('{survey}/{sections}/questions/delete/lang/{questionId}-{langid}', 'AdminQuestionController@destroyLang')->name('questions.lang.destroy');
    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('{survey}/{sections}/questions', 'AdminQuestionController');


    //Admin Survey Kit Answer Management Section Routes


    Route::post('kit/answer/export', 'AdminSurveyKitAnswerController@export')->name('answer.export');
    Route::get('survey/{id}/export', 'AdminSurveyKitAnswerController@getSurveyTemplate')->name('survey.export');
    Route::post('kit/answer/query', 'AdminSurveyKitAnswerController@search')->name('answer.search');

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('kit/answer', 'AdminSurveyKitAnswerController', ['only' => ['index', 'show'] ]);

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('resources', 'AdminResourcesController', ['except' => ['show'] ]);

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('payment', 'AdminPaymentController', ['only' => 'index' ]);

    // Error Logs
    Route::get('error/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('error.logs');

    Route::post('errors/query', 'AdminErrorsController@search')->name('errors.search');
    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('errors', 'AdminErrorsController', ['only' => 'index' ]);

    Route::get("/activity", 'AdminActivityLogController@index')->name('activity.index');
    Route::get("/activity/{date}", 'AdminActivityLogController@show')->name('activity.show');

    Route::get("/contact", 'AdminContactController@index')->name('contact.index');

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    // leader
    Route::get('selling-teams/assign-leader/{id}', 'AdminSellingTeamsController@createLeader')->name('selling-teams.assign-leader.create');
    Route::post('selling-teams/assign-leader/{id}', 'AdminSellingTeamsController@storeLeader')->name('selling-teams.assign-leader.store');
    Route::post('selling-teams/change-leader/{id}', 'AdminSellingTeamsController@changeLeader')->name('selling-teams.change-leader');
    
    // member
    Route::get('selling-teams/add-member/{id}', 'AdminSellingTeamsController@createMember')->name('selling-teams.add-member.create');
    Route::post('selling-teams/assign-member/{id}', 'AdminSellingTeamsController@storeMember')->name('selling-teams.add-member.store');
    Route::delete('selling-teams/destroy-member/{id}', 'AdminSellingTeamsController@destroyMember')->name('selling-teams.destroy-membere');

    //city 
    Route::delete('selling-teams/destroy-city/{selling_team_id}/{city_id}', 'AdminSellingTeamsController@destroyCity')->name('selling-teams.destroy-city');
    Route::post('selling-teams/city/{selling_team_id}', 'AdminSellingTeamsController@storeCity')->name('selling-teams.storecity');

    Route::resource('selling-teams', 'AdminSellingTeamsController');


    Route::get("/test", 'GeneralController@test');
});

/*
|--------------------------------------------------------------------------
| DIETITIAN Route
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'dietitian',  'middleware' => 'dietitian', 'as' => 'dietitian.'], function()
{
    //All the routes that belongs to the group goes here
    Route::get('/','DietitianController@index')->name('index');
    Route::get('/my-order/{tracking}','DietitianController@myOrder')->name('my-order');
    Route::group(['middleware' => 'team-leader'], function () {
        Route::get('/team','DietitianController@team')->name('team');
        Route::get('/team/{refcode}','DietitianController@member')->name('team.member');
        Route::get('/all-orders','DietitianController@AllOrders')->name('team.allorders');
        Route::get('/order/{tracking}','DietitianController@showOrder')->name('team.show.order');
        Route::get('/all-kits','DietitianController@allKits')->name('team.allkits');
        Route::get('/kit/{kitCode}','DietitianController@showKit')->name('team.show.kit');
        Route::get('/kit/generate/{kitCode}','DietitianController@generateKit')->name('team.generate.kit');
    });
    Route::get('/my-kit/{kitCode}','DietitianController@myKit')->name('my-kit');
    Route::get('/my-kit/generate/{kitCode}','DietitianController@generateMyKit')->name('generate.my-kit');
});

/*
|--------------------------------------------------------------------------
| USER Route
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'user',  'middleware' => ['auth', 'verified'], 'as' => 'user.'], function()
{
    //All the routes that belongs to the group goes here
    Route::get('/','UserController@index')->name('index');
    // Create View

    Route::get('/{kitCode}-{kitId}', 'UserController@surveyView')->name('survey.create');
    // Store
    Route::post('/{kitCode}-{kitId}', 'UserController@storeSurvey')->name('survey.store');

    Route::get('/kit/{id}', 'UserController@showAnswer')->name('answer.show');

});



Route::redirect('/colyak-hastaligi', 'gida-hassasiyeti', 301);
Route::redirect('/shop/cift-paketi', '/checkout', 301);
Route::redirect('/bilim', '/', 301);
Route::redirect('/cart', '/', 301);
Route::redirect('/enbiosis-test', '/', 301);
Route::redirect('/index.php', '/', 301);
Route::redirect('/index.php/bilim', '/', 301);
Route::redirect('/index.php/login', '/', 301);
Route::redirect('/index.php/mikrobiyom', '/mikrobiyom', 301);
Route::redirect('/index.php/password/reset', '/', 301);
Route::redirect('/index.php/register-kit', '/', 301);
Route::redirect('/index.php/urunlerimiz', '/urunlerimiz', 301);
Route::redirect('/login', '/', 301);
Route::redirect('/mikrobiyom-analizi', '/urunlerimiz', 301);
Route::redirect('/password/reset', '/', 301);
Route::redirect('/shop/cift-paket', '/', 301);
Route::redirect('/shop/ucludiyet-paket', '/', 301);
Route::redirect('/blog/content-blocks/separators/', '/blog', 301);
Route::redirect('/blog/content-blocks/styled-lists/', '/blog', 301);
Route::redirect('/blog/content-blocks/tabs-pills/', '/blog', 301);
Route::redirect('/blog/content-blocks/instagram-feed/', '/blog', 301);
Route::redirect('/blog/content-blocks/social-links/', '/blog', 301);
Route::redirect('/blog/ornek-sayfa/', '/blog', 301);
Route::redirect('/blog/content-blocks/numbered-headings/', '/blog', 301);
Route::redirect('/blog/galleries/', '/blog', 301);
Route::redirect('/blog/content-blocks/', '/blog', 301);
Route::redirect('/blog/content-blocks/accordions/', '/blog', 301);
Route::redirect('/blog/content-blocks/drop-caps/', '/blog', 301);
Route::redirect('/blog/sample-page/', '/blog', 301);
Route::redirect('/blog/content-blocks/facebook-fanpage/', '/blog', 301);
Route::redirect('/blog/content-blocks/share-buttons/', '/blog', 301);
Route::redirect('/blog/content-blocks/pinterest-board/', '/blog', 301);
Route::redirect('/blog/content-blocks/subscription-forms/', '/blog', 301);
Route::redirect('/blog/contact-form/', '/blog', 301);
Route::redirect('/blog/content-blocks/author/', '/blog', 301);
Route::redirect('/blog/coming-soon/', '/blog', 301);
Route::redirect('/blog/content-blocks/badges/', '/blog', 301);
Route::redirect('/blog/content-blocks/styled-blocks/', '/blog', 301);
Route::redirect('/blog/content-blocks/twitter-feed/', '/blog', 301);
Route::redirect('/blog/content-blocks/alerts/', '/blog', 301);
Route::redirect('/blog/content-blocks/progress-bars/', '/blog', 301);
Route::redirect('/blog/inline-posts/', '/blog', 301);
Route::redirect('/blog/category-blocks/', '/blog', 301);
Route::redirect('/blog/promo-blocks/', '/blog', 301);
Route::redirect('/index.php', '/', 301);
Route::redirect('/index.php/register-kit', '/', 301);

app/SellingTeam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Dietitian;

class SellingTeam extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'leader_id', 'note'
    ];

    public function cities()
    {
        return $this->belongsToMany('App\City', 'selling_team_city');
    }

    public function dietitians()
    {
        return $this->hasMany('App\Dietitian');
    }

    public function getLeaderAttribute()
    {
        if ( $this->leader_id ) {
            $leader = Dietitian::whereId( $this->leader_id )->first();
            if ( $leader )
                return $leader;
            else 
                return null;
        } else
            return null;
    }
}

resources/views/admin/selling-teams/addMember.blade.php
@extends('layouts.admin')
@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Selling Teams</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Admin You are in Add New Members for selling team Section!
                    </div>
                </div>
                @include('include.messages')
                @include('include.form-errors')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    <a  href="{{route('admin.dietitians.create')}}" class="header-table btn btn-outline-success mb-2">Create {{ $team->kind }}</a>
                    <a  href="{{route('admin.selling-teams.show', $team->id)}}" class="header-table btn btn-outline-success mb-2">Show Selling Team</a>
                </div>
                {!! Form::open(['method'=>'POST', 'action' => ['AdminSellingTeamsController@storeMember', $team->id]]) !!}
                
                    <div class="form-group">
                        
                        {!! Form::label('members[]', 'Add New Members:') !!}
                        {!! Form::select('members[]', $dietitians, null, ['class'=>'form-control', 'multiple']) !!}
                        
                    </div>

                    <div class="form-group">
                        {!! Form::submit('Add Member', ['class'=>'btn btn-primary']) !!}
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

@section('script')
 
@endsection

resources/views/admin/selling-teams/assignleader.blade.php
@extends('layouts.admin')
@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Selling Teams</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Admin You are in assign leader for selling team Section!
                    </div>
                </div>
                @include('include.messages')
                @include('include.form-errors')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    <a  href="{{route('admin.selling-teams.index')}}" class="header-table btn btn-outline-success mb-2">Selling Teams</a>
                </div>
                {!! Form::open(['method'=>'POST', 'action' => ['AdminSellingTeamsController@storeLeader', $team->id]]) !!}
                
                    <div class="form-group">
                        
                        {!! Form::label('members[]', 'Assign New Leader:') !!}
                        {!! Form::select('leader_id', $dietitians, null, ['class'=>'form-control', 'placeholder'=>'Please select ...']) !!}
                        
                    </div>

                    <div class="form-group">
                        {!! Form::submit('Assign Leader', ['class'=>'btn btn-primary']) !!}
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

@section('script')
 
@endsection

resources/views/admin/selling-teams/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Selling Teams</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Admin You are in Create Selling Teams Section!
                    </div>
                </div>
                @include('include.messages')
                @include('include.form-errors')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    <a  href="{{route('admin.selling-teams.create')}}" class="header-table btn btn-outline-success mb-2">Create Team</a>
                </div>
                {!! Form::open(['method'=>'POST', 'action' => 'AdminSellingTeamsController@store', 'files'=>true]) !!}

                    <div class="form-row">

                        <div class="form-group col-lg-6">
                    
                            {!! Form::label('name', 'Name:') !!}
                            {!! Form::text('name', null, ['class'=>'form-control']) !!}
                    
                        </div>

                        <div class="form-group col-lg-6">

                            {!! Form::label('note', 'Note') !!}
                            {!! Form::text('note', null, ['class'=>'form-control']) !!}
    
                        </div>

                    </div>
                
                    <div class="form-group" style="height: 500px">
                    
                        {!! Form::label('cities[]', 'Cities:') !!}
                        {!! Form::select('cities[]', $cities, null, ['class'=>'form-control', 'placeholder'=>'Please select ...', 'multiple', 'style' => 'height:90%']) !!}
                        
                    </div>

                    <div class="form-group">
                        {!! Form::submit('Create Team', ['class'=>'btn btn-primary']) !!}
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

@section('script')
 
@endsection

resources/views/admin/selling-teams/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Selling Teams</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Admin You are in Selling Teams Section!
                    </div>
                </div>
                @include('include.messages')
                @include('include.form-errors')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    <a  href="{{route('admin.selling-teams.create')}}" class="header-table btn btn-outline-success mb-2">Create Team</a>
                </div>
                <table class="table table-responsive-lg table-striped">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Leader</th>
                        <th scope="col">Note</th>
                        <th scope="col">Members conut</th>
                        <th scope="col">cities</th>
                        <th scope="col">Created</th>
                        <th scope="col">process</th>
                    </tr>
                    </thead>
                    <tbody>
                        @if ($teams)
                            @foreach ($teams as $team)
                                <tr>
                                    <td>{{$team->id}}</td>
                                    <td>{{$team->name}}</td>
                                    <td>{!! $team->Leader ? $team->Leader->name . ' - ' . $team->Leader->reference_code : '<a href="' . route('admin.selling-teams.assign-leader.create', $team->id) . '" class="header-table btn btn-outline-danger"> Assign a Leader </a>'!!}</td>
                                    <td>{!! $team->note ? $team->note : '<span class="text-danger"> Not Entered </span>' !!}</td>
                                    <td>{{$team->dietitians()->count()}}</td>
                                    <td>{!! $team->cities ? $team->cities->count() : '<span class="text-danger"> Not Entered </span>' !!}</td>
                                    <td>{{$team->created_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>
                                    <td>
                                        <a href="{{route('admin.selling-teams.show', $team->id)}}" class="btn btn-outline-info mr-2 mb-1" >Show</a>
                                        <a href="#" data-toggle="modal" data-target="#update_{{ $team->id }}" class="btn btn-outline-success mr-2 mb-1" >Update</a>
                                        {!! Form::open(['method'=>'DELETE', 'action' => ['AdminSellingTeamsController@destroy', $team->id], 'style'=> 'display:inline']) !!}
                                            {!! Form::submit('Delete', ['class'=>'btn btn-outline-danger mr-2 mb-1','onclick'=>"return confirm('Silmek isteğinizden Emin misiniz?')"]) !!}
                                        {!! Form::close() !!} 
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
            <div class="text-center my-4">
                {{$teams->links()}}
            </div>
        </div>
    </div>
    @if ($teams)
        @foreach ($teams as $team)
            <!-- Modal -->
            <div class="modal fade" id="update_{{ $team->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle">Create Admin</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            {{-- {!! Form::open(['method'=>'DELETE', 'action' => ['AdminCouponController@destroy', $coupon->id], 'style'=> 'display:inline', 'id' => 'id_form_' . $coupon->code]) !!} --}}
                            {!! Form::open(['method'=>'PATCH', 'action' => ['AdminSellingTeamsController@update', $team->id], 'style'=> 'display:inline', 'id' => $team->id . '_form_update', 'files'=>true]) !!}
                                <div class="form-group">

                                    {!! Form::label($team->id . '_name', 'Name') !!}
                                    {!! Form::text($team->id . '_name', $team->name, ['class'=>'form-control']) !!}
                    
                                </div>
                                <div class="form-group">

                                    {!! Form::label($team->id . '_note', 'note') !!}
                                    {!! Form::text($team->id . '_note', $team->note, ['class'=>'form-control']) !!}
                    
                                </div>
                            {!! Form::close() !!} 
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button class="btn btn-primary" onclick="event.preventDefault();document.getElementById('{{$team->id}}_form_update').submit();">
                                Save Changes
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @endif
@endsection