routes/web.php
// Route::post('campaign-update-cart/{campaignCode}', 'ShopCampaignController@updateQuantity')->name('checkout.Campaign.updatecart');

// // get instalments table
// Route::post('campaign-instalments-table/{campaignCode}', 'ShopCampaignController@campaignInstalmentsTable')->name('checkout.campaign.instalmentsTable');

// // Submit CheckOut campaign Form
// Route::post('checkout/{campaignCode}/{slug}', 'ShopCampaignController@CheckOut')->name('checkout.campaign.submit');

// // Submit CheckOut result campaign Form
// Route::post('checkout-result/{campaignCode}/{slug}', 'ShopCampaignController@CheckOutResult')->name('checkout.campaign.result');
/*
|--------------------------------------------------------------------------
|   Auth Routes For User
|--------------------------------------------------------------------------
*/
Auth::routes(['verify' => true, 'register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

// Register kit Routes
Route::get('register-kit', 'Auth\UserRegisterKitController@showRegisterKitForm')->name('register-kit.form');
Route::post('register-kit', 'Auth\UserRegisterKitController@RegisterKit')->name('register-kit');

Route::get('register-kit-user', 'Auth\UserRegisterKitController@showRegisterKitWithUserForm')->name('register-kit-user.form');
Route::post('register-kit-user', 'Auth\UserRegisterKitController@registerKitWithUser')->name('register-kit-user');
Route::post('login-kit-user', 'Auth\UserRegisterKitController@LoginUserAfterKitCodeMatch')->name('login-kit-user');


/*
|--------------------------------------------------------------------------
| Login and Loguot Routes For Admin
|--------------------------------------------------------------------------
*/
Route::prefix('admin')->group(function() {

    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    // Route::get('/', 'AdminController@index')->name('admin.index');
}) ;

/*
|--------------------------------------------------------------------------
| Login and Loguot Routes For dietitian
|--------------------------------------------------------------------------
*/
Route::prefix('dietitian')->group(function() {

    Route::get('/login','Auth\DietitianLoginController@showLoginForm')->name('dietitian.login');
    Route::post('/login', 'Auth\DietitianLoginController@login')->name('dietitian.login.submit');
    Route::post('logout/', 'Auth\DietitianLoginController@logout')->name('dietitian.logout');
    // Route::get('/', 'DietitianController@index')->name('dietitian.index');
}) ;



/*
|--------------------------------------------------------------------------
| ADMIN Route
|--------------------------------------------------------------------------
*/
Route::get('/admin','AdminController@index')->middleware(['auth:admin', 'admin'])->name('admin.index');
Route::patch('/admin/profile','AdminController@updateProfile')->name('admin.updateProfile');
// operation admin
Route::group(['prefix' => 'operation',  'middleware' => ['auth:admin', 'admin', 'op-admin'], 'as' => 'operation.'], function()
{
    Route::get('/','OperationAdminController@indexRoute')->name('index');
    Route::get('/profile','AdminController@OperationAdminProfile')->name('profile');

    // Admin Orders MAnagement Section Routes
    Route::post('/orders/query', 'OperationAdminController@search')->name('orders.search');
    Route::get('/orders/export', 'OperationAdminController@export')->name('orders.export');
    Route::patch('/kit/{kit}', 'OperationAdminController@updateKit')->name('kit.update');
    Route::post('/kit/delever', 'OperationAdminController@kitDeleverToUser')->name('kit.delever');
    Route::post('/kit/received', 'OperationAdminController@kitReceived')->name('kit.received');
    Route::post('/kit/sent', 'OperationAdminController@kitSentToLab')->name('kit.sent');

    Route::get('/kits', 'OperationAdminController@Kit')->name('kit');
    Route::post('/kits/query', 'OperationAdminController@Kitsearch')->name('kit.search');

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('orders', 'OperationAdminController');

});

// laboratory admin
Route::group(['prefix' => 'laboratory',  'middleware' => ['auth:admin', 'admin', 'lab-admin'], 'as' => 'lab.'], function()
{

    Route::get('/','LaboratoryAdminController@indexRoute')->name('index');

    Route::get('/profile','AdminController@LabAdminprofile')->name('profile');

    // answers
    Route::get('answer', 'LaboratoryAdminController@indexAnswer')->name('answer.index');
    Route::post('kit/answer/export', 'LaboratoryAdminController@export')->name('answer.export');
    Route::post('kit/answer/query', 'LaboratoryAdminController@search')->name('answer.search');
    Route::get('kit/answer/{kit_code}', 'LaboratoryAdminController@show')->name('answer.show');


    //kit
    Route::post('kit/upload/food', 'LaboratoryAdminController@uploadFoodJsonFile')->name('food.upload');
    Route::post('kit/upload/microbiome', 'LaboratoryAdminController@uploadMicrobiomeJsonFile')->name('microbiome.upload');
    Route::get('generate/{id}', 'LaboratoryAdminController@Generate')->name('pdf.generate');
});

// Super Admin
Route::group(['prefix' => 'admin',  'middleware' => ['auth:admin', 'admin', 'superAdmin'], 'as' => 'admin.'], function()
{

    Route::get('/dashboard','AdminDashboardController@index')->name('dashboard');

    Route::get('/profile','AdminController@SuperAdminprofile')->name('profile');
    //All the routes that belongs to the group goes here

    // Admin Admin Management Section Routes

    Route::get('/admins/trash', 'AdminAdminsController@trash')->name('admins.trash');
    Route::get('/admins/{id}/restore', 'AdminAdminsController@restore')->name('admins.restore');

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('admins', 'AdminAdminsController');

    // Admin User Management Section Routes

    Route::get('/users/trash', 'AdminUsersController@trash')->name('users.trash');
    Route::get('/users/{id}/restore', 'AdminUsersController@restore')->name('users.restore');
    Route::post('/users/query', 'AdminUsersController@search')->name('users.search');
    Route::post('/users/link/{user}', 'AdminUsersController@link')->name('kitlink');


    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('users', 'AdminUsersController');

    //Admin Prodcuts MAnagement Section Routes

    Route::get('/products/trash', 'AdminProductsController@trash')->name('products.trash');
    Route::get('/products/{id}/restore', 'AdminProductsController@restore')->name('products.restore');
    Route::get('/products/show/{id}/{slug}', 'AdminProductsController@show')->name('products.show');
    Route::post('/products/query', 'AdminProductsController@search')->name('products.search');

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('products', 'AdminProductsController', ['except' => ['show'] ] );

    //Admin Coupon MAnagement Section Routes

    Route::get('/coupons/notAvailableCoupons', 'AdminCouponController@notAvailableCoupons')->name('coupons.notAvailableCoupons');
    // Route::get('/coupons/awardedCoupons', 'AdminCouponController@awardedCoupons')->name('coupons.awardedCoupons');
    // Route::post('/coupons/updateGiveOrTake/{id}', 'AdminCouponController@updateGiveOrTake')->name('coupons.updateGiveOrTake');
    Route::post('/coupons/query', 'AdminCouponController@search')->name('coupons.search');


    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('coupons', 'AdminCouponController', ['except' => ['show'] ] );


     //Admin campaigns MAnagement Section Routes
    Route::get('/campaigns/notAvailablecampaigns', 'AdminCampaignController@notAvailableCampaigns')->name('campaigns.not');
 
     /*
     *   if you want to Add new methods to a resource controller in Laravel
     *   Just add a route to that method separately, before you register the resource:
     */
     Route::resource('campaigns', 'AdminCampaignController');

    //Admin Dietitians MAnagement Section Routes

    Route::get('/dietitians/trash', 'AdminDietitiansController@trash')->name('dietitians.trash');
    Route::get('/dietitians/{id}/restore', 'AdminDietitiansController@restore')->name('dietitians.restore');
    Route::post('/dietitians/link/{dietitian}', 'AdminDietitiansController@kitLink')->name('dietitians.kitlink');


    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('dietitians', 'AdminDietitiansController');

    //Admin Orders MAnagement Section Routes
    Route::post('/orders/query', 'AdminOrdersController@search')->name('orders.search');
    Route::get('/orders/export', 'AdminOrdersController@export')->name('orders.export');
    //Admin Orders MAnagement Section Routes
    Route::post('/orders/{id}/assign-ref-code', 'AdminOrdersController@assignRefCode')->name('orders.assign-ref-code');


    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\City;
use App\County;

class Order extends Model
{
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'tracking', 'payment_id', 'coupon_id', 'status', 'address',
        'name', 'email', 'dietitian_code', 'phone', 'price', 'checkbox',
        'cc_name', 'card_number', 'expiration_month', 'expiration_year', 'cvc',
        'city', 'county', 'fcity_id', 'fcounty_id', 'faddress'
    ];

     /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'cc_name', 'card_number', 'expiration_month', 'expiration_year', 'cvc'
    ];

    /**
     * Get the payment record associated with the Order.
     */
    public function payment()
    {
        return $this->belongsTo('App\Payment');
    }

    public function coupon()
    {
        return $this->belongsTo('App\Coupon');
    }

    public function orderDetail()
    {
        return $this->hasMany('App\OrderDetail', 'order_id');
    }

    public function city(){
        return $this->belongsTo('App\City');
    }

    public function county(){
        return $this->belongsTo('App\County');
    }

    public function dietitian()
    {
        return $this->belongsTo('App\Dietitian', 'dietitian_code', 'reference_code');
    }

    public function getBiCityAttribute()
    {
        if ( $this->fcity_id ) {
            return City::find($this->fcity_id);
        }
    }
    public function getBiCountyAttribute()
    {
        if ( $this->fcounty_id ) {
            return County::find($this->fcounty_id);
        }
    }
    public function getOrderStatusAttribute()
    {
        if($this->status == 0)
            return '<span class="text-dark"> order reserved </span>';
    }

    public function setDietitianCodeAttribute($value)
    {
        $this->attributes['dietitian_code'] = strtoupper($value);
    }
}

resources/views/admin-operation/order/index.blade.php
@extends('layouts.admin-operation')
@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Orders</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Operation Admin You are in Orders Section!
                    </div>
                </div>
                @include('include.messages')
                @include('include.form-errors')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    {{-- <a  href="{{route('admin.users.create')}}" class="header-table btn btn-outline-success mb-2">Create User</a>
                    <a  href="{{route('admin.users.trash')}}" class="header-table btn btn-outline-danger mb-2">User trash</a> --}}
                    <a  href="{{route('operation.orders.export')}}" class="header-table btn btn-outline-success mb-2">Export All</a>
                    {!! Form::open(['method'=>'POST', 'action' => ['OperationAdminController@search'], 'style'=> 'display:inline']) !!}

                        {!! Form::label('search', 'Query:') !!}
                        {!! Form::text('search', null, ['class'=>'form-control', 'style'=> 'display:inline; width:initial', 'required']) !!}

                        {!! Form::submit('search', ['class'=>'btn btn-outline-success mr-2 mb-1']) !!}

                    {!! Form::close() !!} 
                </div>
                <table class="table table-responsive-lg table-striped">
                    <thead class="thead-light">
                    <tr>
                       <th>#</th>
                       <th>Traking Number</th>
                       <th>name</th>
                       <th>phone</th>
                       <th>address</th>
                       <th>dietitian_code</th>
                       <th>Created</th>
                       <th>Updated</th>
                       <th>process</th>
                    </tr>
                    </thead>
                    <tbody>
                        @if ($orders)
                            @foreach ($orders as $order)
                            <tr>
                                <td>{{$order->id}}</td>
                                <td>{{$order->tracking}}</td>
                                <td>{{$order->name}}</td>
                                <td>{{$order->phone}}</td>
                                <td>{{$order->address}} - {{$order->city ? $order->city->city : ''}} - {{ $order->county ? $order->county->county : '' }}</td>
                                <td>{{$order->dietitian_code ?? 'not Entered'}}</td>
                                <td>{{$order->updated_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>
                                <td>{{$order->created_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>   
                                <td>
                                    <a href="{{route('operation.orders.show', $order->id)}}" class="btn btn-outline-info mr-2 mb-1" >Show Order Details</a>
                                </td>
                           </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
            <div class="text-center my-4">
                {{$orders->links()}}
            </div>
        </div>
    </div>
    {{-- {{print_r($orders)}} --}}
@endsection

resources/views/admin-operation/order/search.blade.php
@extends('layouts.admin-operation')
@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Orders</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Operation Admin You are in Orders Section!
                    </div>
                </div>
                @include('include.messages')
                @include('include.form-errors')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    {{-- <a  href="{{route('admin.users.create')}}" class="header-table btn btn-outline-success mb-2">Create User</a>
                    <a  href="{{route('admin.users.trash')}}" class="header-table btn btn-outline-danger mb-2">User trash</a> --}}
                    <a  href="{{route('operation.orders.index')}}" class="header-table btn btn-outline-success mb-2">Go to order index page</a>
                    {!! Form::open(['method'=>'POST', 'action' => ['OperationAdminController@search'], 'style'=> 'display:inline']) !!}

                        {!! Form::label('search', 'Query:') !!}
                        {!! Form::text('search', null, ['class'=>'form-control', 'style'=> 'display:inline; width:initial', 'required']) !!}

                        {!! Form::submit('search', ['class'=>'btn btn-outline-success mr-2 mb-1']) !!}

                    {!! Form::close() !!} 
                </div>
                <table class="table table-responsive-lg table-striped">
                    <thead class="thead-light">
                    <tr>
                       <th>#</th>
                       <th>Traking Number</th>
                       <th>name</th>
                       <th>phone</th>
                       <th>address</th>
                       <th>dietitian_code</th>
                       <th>Created</th>
                       <th>Updated</th>
                       <th>process</th>
                    </tr>
                    </thead>
                    <tbody>
                        @if ($orders)
                            @foreach ($orders as $order)
                            <tr>
                                <td>{{$order->id}}</td>
                                <td>{{$order->tracking}}</td>
                                <td>{{$order->name}}</td>
                                <td>{{$order->phone}}</td>
                                <td>{{$order->address}} - {{$order->city ? $order->city->city : ''}} - {{ $order->county ? $order->county->county : '' }}</td>
                                <td>{{$order->dietitian_code ?? 'not Entered'}}</td>
                                <td>{{$order->updated_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>
                                <td>{{$order->created_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>   
                                <td>
                                    <a href="{{route('operation.orders.show', $order->id)}}" class="btn btn-outline-info mr-2 mb-1" >Show Order Details</a>
                                </td>
                           </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {{-- {{print_r($orders)}} --}}
@endsection