routes/web.php
// Route::get('prof-dr-tarkan-karakan', 'GeneralController@profDrTarkanKarakan')->name('prof-dr-tarkan-karakan');

// //Prof. Dr. Halil Coşkun

// Route::get('prof-dr-halil-coskun', 'GeneralController@profDrHalilCoskun')->name('prof-dr-halil-coskun');

// //Dr. Özkan Ufuk Nalbantoğlu

// Route::get('dr-ozkan-ufuk-nalbantoglu', 'GeneralController@drOzkanUfukNalbantoglu')->name('dr-ozkan-ufuk-nalbantoglu');

// //Doç. Dr. Aycan Gündoğdu

// Route::get('doc-dr-aycan-gundogdu', 'GeneralController@docDrAycanGundogdu')->name('doc-dr-aycan-gundogdu');

// //Doç. Dr. Aycan Gündoğdu

// Route::get('ceo-omer-ozkan', 'GeneralController@ceoOmerOzkan')->name('ceo-omer-ozkan');

/*
|--------------------------------------------------------------------------
| Lang Route
|--------------------------------------------------------------------------
*/
Route::get('locale/{locale}', 'GeneralController@locale')->name('lang');

// For Ajax Request For updata and remove items from cart
Route::post('update-cart', 'ShopController@updateCartProduct');

Route::post('installment', 'ShopController@installment');
// Show CheckOut Form
Route::get('checkout', 'CheckoutController@index')->name('checkout');
// Get County based in City
Route::post('getCounty', 'ShopController@getCounty')->name('getCounty');
// get instalments table
Route::post('instalmentsTable', 'GeneralController@instalmentsTable')->name('instalmentsTable');
// Check for Coupon  Form
Route::post('checkForCoupon', 'ShopController@checkForCoupon')->name('checkForCoupon');
// Remove Coupon From Payment form
Route::post('removeCouponFromPaymentForm', 'ShopController@removeCouponFromPaymentForm')->name('removeCouponFromPaymentForm');

// Show CheckOut For prodduct
Route::get('checkout/{slug}', 'ShopController@showCheckOut')->name('checkout.product');
// Submit CheckOut For prodduct
Route::post('checkout/{slug}', 'ShopController@CheckOut')->name('checkout.product.submit');


// Route For get POST Requset from bank api for results
Route::post('checkout-result/{slug}', 'ShopController@CheckOutResult')->name('checkout.result.p');

Route::get('/tesekkurler/{slug}/{traking}', 'GeneralController@tesekkurler')->name('tesekkurler');

//campaign pages
// Show campaign CheckOut Page
// Route::get('kampanya', 'CheckoutController@campaign')->name('Campaign');
// // // Show campaign CheckOut Page
// Route::get('kampanya/{campaignCode}', 'CheckoutController@campaignIndex')->name('checkout.Campaign');
// // // Show campaign CheckOut form
// Route::get('checkout/{campaignCode}/{slug}', 'ShopCampaignController@index')->name('checkout.Campaign.index');

// // updaate kit quantity in campaign 
// Route::post('campaign-update-cart/{campaignCode}', 'ShopCampaignController@updateQuantity')->name('checkout.Campaign.updatecart');

// // get instalments table
// Route::post('campaign-instalments-table/{campaignCode}', 'ShopCampaignController@campaignInstalmentsTable')->name('checkout.campaign.instalmentsTable');

// // Submit CheckOut campaign Form
// Route::post('checkout/{campaignCode}/{slug}', 'ShopCampaignController@CheckOut')->name('checkout.campaign.submit');

// // Submit CheckOut result campaign Form
// Route::post('checkout-result/{campaignCode}/{slug}', 'ShopCampaignController@CheckOutResult')->name('checkout.campaign.result');
/*
|--------------------------------------------------------------------------
|   Auth Routes For User
|--------------------------------------------------------------------------
*/
Auth::routes(['verify' => true, 'register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

// Register kit Routes
Route::get('register-kit', 'Auth\UserRegisterKitController@showRegisterKitForm')->name('register-kit.form');
Route::post('register-kit', 'Auth\UserRegisterKitController@RegisterKit')->name('register-kit');

Route::get('register-kit-user', 'Auth\UserRegisterKitController@showRegisterKitWithUserForm')->name('register-kit-user.form');
Route::post('register-kit-user', 'Auth\UserRegisterKitController@registerKitWithUser')->name('register-kit-user');
Route::post('login-kit-user', 'Auth\UserRegisterKitController@LoginUserAfterKitCodeMatch')->name('login-kit-user');


/*
|--------------------------------------------------------------------------
| Login and Loguot Routes For Admin
|--------------------------------------------------------------------------
*/
Route::prefix('admin')->group(function() {

    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    // Route::get('/', 'AdminController@index')->name('admin.index');
}) ;

/*
|--------------------------------------------------------------------------
| Login and Loguot Routes For dietitian
|--------------------------------------------------------------------------
*/
Route::prefix('dietitian')->group(function() {

    Route::get('/login','Auth\DietitianLoginController@showLoginForm')->name('dietitian.login');
    Route::post('/login', 'Auth\DietitianLoginController@login')->name('dietitian.login.submit');
    Route::post('logout/', 'Auth\DietitianLoginController@logout')->name('dietitian.logout');
    // Route::get('/', 'DietitianController@index')->name('dietitian.index');
}) ;



/*
|--------------------------------------------------------------------------
| ADMIN Route
|--------------------------------------------------------------------------
*/
Route::get('/admin','AdminController@index')->middleware(['auth:admin', 'admin'])->name('admin.index');
Route::patch('/admin/profile','AdminController@updateProfile')->name('admin.updateProfile');
// operation admin
Route::group(['prefix' => 'operation',  'middleware' => ['auth:admin', 'admin', 'op-admin'], 'as' => 'operation.'], function()
{
    Route::get('/','OperationAdminController@indexRoute')->name('index');
    Route::get('/profile','AdminController@OperationAdminProfile')->name('profile');

    // Admin Orders MAnagement Section Routes
    Route::post('/orders/query', 'OperationAdminController@search')->name('orders.search');
    Route::get('/orders/export', 'OperationAdminController@export')->name('orders.export');
    Route::patch('/kit/{kit}', 'OperationAdminController@updateKit')->name('kit.update');
    Route::post('/kit/delever', 'OperationAdminController@kitDeleverToUser')->name('kit.delever');
    Route::post('/kit/received', 'OperationAdminController@kitReceived')->name('kit.received');
    Route::post('/kit/sent', 'OperationAdminController@kitSentToLab')->name('kit.sent');

    Route::get('/kits', 'OperationAdminController@Kit')->name('kit');
    Route::post('/kits/query', 'OperationAdminController@Kitsearch')->name('kit.search');

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('orders', 'OperationAdminController');

});

// laboratory admin
Route::group(['prefix' => 'laboratory',  'middleware' => ['auth:admin', 'admin', 'lab-admin'], 'as' => 'lab.'], function()
{

    Route::get('/','LaboratoryAdminController@indexRoute')->name('index');

    Route::get('/profile','AdminController@LabAdminprofile')->name('profile');

    // answers
    Route::get('answer', 'LaboratoryAdminController@indexAnswer')->name('answer.index');
    Route::post('kit/answer/export', 'LaboratoryAdminController@export')->name('answer.export');
    Route::post('kit/answer/query', 'LaboratoryAdminController@search')->name('answer.search');
    Route::get('kit/answer/{kit_code}', 'LaboratoryAdminController@show')->name('answer.show');


    //kit
    Route::post('kit/upload/food', 'LaboratoryAdminController@uploadFoodJsonFile')->name('food.upload');
    Route::post('kit/upload/microbiome', 'LaboratoryAdminController@uploadMicrobiomeJsonFile')->name('microbiome.upload');
    Route::get('generate/{id}', 'LaboratoryAdminController@Generate')->name('pdf.generate');
});

// Super Admin
Route::group(['prefix' => 'admin',  'middleware' => ['auth:admin', 'admin', 'superAdmin'], 'as' => 'admin.'], function()
{

    Route::get('/dashboard','AdminDashboardController@index')->name('dashboard');

    Route::get('/profile','AdminController@SuperAdminprofile')->name('profile');
    //All the routes that belongs to the group goes here

    // Admin Admin Management Section Routes

    Route::get('/admins/trash', 'AdminAdminsController@trash')->name('admins.trash');
    Route::get('/admins/{id}/restore', 'AdminAdminsController@restore')->name('admins.restore');

    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('admins', 'AdminAdminsController');

    // Admin User Management Section Routes

    Route::get('/users/trash', 'AdminUsersController@trash')->name('users.trash');
    Route::get('/users/{id}/restore', 'AdminUsersController@restore')->name('users.restore');
    Route::post('/users/query', 'AdminUsersController@search')->name('users.search');
    Route::post('/users/link/{user}', 'AdminUsersController@link')->name('kitlink');


    /*
    *   if you want to Add new methods to a resource controller in Laravel
    *   Just add a route to that method separately, before you register the resource:
    */
    Route::resource('users', 'AdminUsersController');

    //Admin Prodcuts MAnagement Section Routes

    Route::get('/products/trash', 'AdminProductsController@trash')->name('products.trash');
    Route::get('/products/{id}/restore', 'AdminProductsController@restore')->name('products.restore');
    Route::get('/products/show/{id}/{slug}', 'AdminProductsController@show')->name('products.show');
    Route::post('/products/query', 'AdminProductsController@search')->name('products.search');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, SoftDeletes, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'address', 'phone', 'gender', 'vegetarian', 'verify_code', 'expires_at', 'date_of_birth', 'email_verified_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'verify_code', 'expires_at',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'expires_at' => 'datetime',
        'date_of_birth' => 'date:Y-m-d',
        'vegetarian' => 'boolean',

    ];
    
    public function photo()
    {
        return $this->morphOne('App\Photo', 'imageable');
    }

    // User Can HAve A mmulti Kit 
    public function Kits()
    {
        return $this->hasMany('App\Kit')->orderBy('registered_at', 'DESC');   
    }

    //Get Gender
    public function getUserGenderAttribute()
    {
        if($this->gender == 0)
            return __('app.belirtilmemiş');
        elseif($this->gender == 1)
            return __('app.erkek');
        elseif($this->gender == 2)
            return __('app.kadin');
        else
            return __('app.belirtilmemiş');
    }

    // // Define an Accessor
    // public function getVegetarianAttribute($value)
    // {
    //     if ( $value ) {
    //         return 'yes';
    //     } else {
    //         return 'no';
    //     }
    // }
    public function getAgeAttribute()
    {
        if ( $this->date_of_birth ){
            $years = \Carbon\Carbon::parse($this->date_of_birth)->age;
            return $years;
        } else {
            return null;
        }
    }
    public function getStrRoleAttribute()
    {
        return 'Normal User';
    }
}

app/Http/Controllers/API/user/AuthController.php
<?php

namespace App\Http\Controllers\API\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\SendsPasswordResetEmails;
use Validator;

class AuthController extends Controller
{
    //
    use SendsPasswordResetEmails;
    /**
     * Handles Login Request
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function login(Request $request)
    { 
        $rules = array(  
            'email' => 'required|email:rfc,dns',
            'password' => 'required|min:6', 
        );
        //Validation
        $data = $request->all();
        $validator = Validator::make($data, $rules); 

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors(), 'code' => 400], 400);  
        } 
 
        if (auth()->attempt($data)) {
            $token = auth()->user()->createToken('TutsForWeb')->accessToken;
            $user = auth()->user();
            $user->kits;
            $this->loginlogout('apiUser', 'user with email: '. $user->email . ' login successful');
            return response()->json(
                [ 'message' => __('api.login_successfully'), 'code' => 200, 'data' => [ 'token' => $token, 'user' => $user ] ],
                200
            );
        } else {
            $this->loginlogout('apiUser', 'user with email: '. $request->email . ' login unsuccessful');
            return response()->json( ['errors' => __('api.login_unsuccessful'), 'code' => 401 ], 401 );
        }
    } 
}

app/Http/Controllers/API/user/PasswordResetController.php
<?php

namespace App\Http\Controllers\API\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Mail\ResetPassword;
use Validator;
use App\User;
use Hash;
use Mail;
use DB;

class PasswordResetController extends Controller
{
    /**
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function passwordreset(Request $request)
    {
        $rules = array(  
            'email' => 'required|email:rfc,dns',
        );
        //Validation
        $data = $request->all();
        $validator = Validator::make($data, $rules); 

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors(), 'code' => 400], 400);  
        }
        if ( $user = User::where('email', '=', $request->email)->first() ) {
            DB::table('password_resets')->whereEmail($request->email)->whereGuard('user')->delete();
            //Create Password Reset Token
            DB::table('password_resets')->insert([
                'email' => $request->email,
                'token' => str_replace('/', '', bcrypt( $request->email . time() ) ),
                'guard' => 'user',
                'created_at' => now()
            ]);
            //Get the token just created above
            $tokenData = DB::table('password_resets')
                ->where('email', $request->email)
                ->whereGuard('user')
                ->first();

            if ($this->sendResetEmail($user, $tokenData->token)) {
                $this->loginlogout('apiUser', 'Password reset url has been sended to this email: ' . $request->email);
                return response()->json( [ 'message' => __('api.send_reset_password'), 'code' => 200 ], 200 );
            } else {
                return response()->json([ 'errors' =>[ __('api.genel_hata') ], 'code' => 400 ], 400 );
            }
        } else {
            $this->loginlogout('apiUser', 'Trying to reset password on email that we don\'t have in our recorder');
            return response()->json(['errors' => [ 'email' => __('api.reset_password_error')], 'code' => 400], 400);  
        }
    }
    public function checkAndReset(Request $request)
    {
        
        $rules = array(
            'password' => 'required|min:6',
            'password_confirmation' => 'required_with:password|same:password|min:6',
            'token' => 'required'
        );
        //Validation
        $data = $request->all();
        $validator = Validator::make($data, $rules); 

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors(), 'code' => 400], 400); 
        }

        $tokenData = DB::table('password_resets')->where('token', urldecode( $request->token ))->first();
        if (!$tokenData)
            return response()->json(['errors' => [__('api.genel_hata')], 'code' => 400], 400);

        $user = User::where('email', $tokenData->email)->first();
        if (!$user)
            return response()->json(['errors' => [__('api.genel_hata')], 'code' => 400], 400);

        $user->password = Hash::make($request->password);
        $user->save(); 
    
        //Delete the token
        DB::table('password_resets')->whereEmail($user->email)->whereGuard('user')->delete();

        $this->loginlogout('apiUser', 'Password reset for this email: ' . $user->email . ' done successfully');
        return response()->json( ['message' => __('api.reset_password_done'), 'code' => 200], 200 );

    }

    private function sendResetEmail(User $user, $token)
    {
        //Generate, the password reset link. The token generated is embedded in the link
        $link = 'https://app.enbiosis.com/password/reset/' . urlencode ( $token );

        try {
            Mail::to($user->email)->locale(app()->getLocale())->send( new ResetPassword( $link ) );
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }
}

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Users</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Admin You are in Users Section!
                    </div>
                </div>
                @include('include.messages')
                @include('include.form-errors')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    <a  href="{{route('admin.users.create')}}" class="header-table btn btn-outline-success mb-2">Create User</a>
                    <a  href="{{route('admin.users.trash')}}" class="header-table btn btn-outline-danger mb-2">User trash</a>
                    {!! Form::open(['method'=>'POST', 'action' => ['AdminUsersController@search'], 'style'=> 'display:inline']) !!}

                        {!! Form::label('search', 'Query:') !!}
                        {!! Form::text('search', null, ['class'=>'form-control', 'style'=> 'display:inline; width:initial', 'required']) !!}

                        {!! Form::submit('search', ['class'=>'btn btn-outline-success mr-2 mb-1']) !!}

                    {!! Form::close() !!} 
                </div>
                <table class="table table-responsive-lg table-striped">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Photo</th>
                        <th scope="col">Name</th>
                        <th scope="col">Gender</th>
                        <th scope="col">date Of Birth</th>
                        <th scope="col">Email</th>
                        <th scope="col">Status</th>
                        <th scope="col">Adress</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Created</th>
                        {{-- <th scope="col">Updated</th> --}}
                        <th scope="col">process</th>
                    </tr>
                    </thead>
                    <tbody>
                        @if ($users)
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td><img class='img-rounded' height="50" src="{{$user->photo ? url('/') . '/img/private/' . $user->photo->path : url('/') . '/img/private/default.png'}}" alt=""></td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->userGender}}</td>
                                    <td>{!! $user->date_of_birth ? $user->age . ' year ' : '<span class="text-danger"> Not Entered </span>'!!}</td>
                                    <td>{{$user->email}}</td>
                                    {!! $user->email_verified_at == NULL ? '<td class="text-danger">Email Not Verified</td>' : '<td class="text-success">Email Verified</td>' !!}
                                    <td>{{$user->address}}</td>
                                    <td>{{$user->phone}}</td>
                                    <td>{{$user->created_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>
                                    {{-- <td>{{$user->updated_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td> --}}
                                    <td>
                                        <a href="{{route('admin.users.show', $user->id)}}" class="btn btn-outline-info mr-2 mb-1" >Show Profile</a>
                                        <a   href="{{route('admin.users.edit', $user->id)}}"	class="btn btn-outline-success update mr-2 mb-1">Update</a>
                                        {!! Form::open(['method'=>'DELETE', 'action' => ['AdminUsersController@destroy', $user->id], 'style'=> 'display:inline']) !!}
                                            {!! Form::submit('Delete', ['class'=>'btn btn-outline-danger mr-2 mb-1','onclick'=>"return confirm('Silmek isteğinizden Emin misiniz?')"]) !!}
                                        {!! Form::close() !!} 
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
            <div class="text-center my-4">
                {{$users->links()}}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/restore.blade.php
@extends('layouts.admin')

@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Users</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Admin You are in Users Trash Section!
                    </div>
                </div>
                @include('include.messages')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    <a  href="{{route('admin.users.create')}}" class="header-table btn btn-outline-success mb-2">Create User</a>
                    <a  href="{{route('admin.users.index')}}" class="header-table btn btn-outline-danger mb-2">User</a>
                </div>
                <table class="table table-responsive-lg table-striped">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Photo</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Status</th>
                            <th scope="col">Adress</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Created</th>
                            <th scope="col">Updated</th>
                            <th scope="col">process</th>
                        </tr>
                        </thead>
                        <tbody>
                            @if ($users)
                                @foreach ($users as $user)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td><img class='img-rounded' height="50" src="{{$user->photo ? url('/') . '/img/private/' . $user->photo->path : url('/') . '/img/private/default.png'}}" alt=""></td>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        {!! $user->email_verified_at == NULL ? '<td class="text-danger">Email Not Verified</td>' : '<td class="text-info">Email Verified</td>' !!}
                                        <td>{{$user->address}}</td>
                                        <td>{{$user->phone}}</td>
                                        <td>{{$user->created_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>
                                        <td>{{$user->updated_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>
                        <td>
                            <a   href="{{route('admin.users.restore', $user->id)}}"	class="btn btn-outline-success update mr-2 mb-1">Restore</a>   
                            {!! Form::open(['method'=>'DELETE', 'action' => ['AdminUsersController@destroy', $user->id, 'soft' => '1'], 'style'=> 'display:inline']) !!}
                                {!! Form::submit('Delete Permanently', ['class'=>'btn btn-outline-danger mr-2 mb-1','onclick'=>"return confirm('Silmek isteğinizden Emin misiniz?')"]) !!}
                            {!! Form::close() !!} 
                        </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    </div>
    <div class="col-lg-12 text-center my-4">
        {{$users->links()}}
    </div>
</div>
</div>
@endsection

resources/views/admin/user/search.blade.php
@extends('layouts.admin')
@section('content')
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-dark text-light">Users</div>

                    <div class="card-body ">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        You are logged in as Admin You are in Users Search Result Section!
                    </div>
                </div>
                @include('include.messages')
                @include('include.form-errors')
            </div>
        </div>
    </div>
    <div class="mt-3 mx-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="text-right">
                    <a  href="{{route('admin.users.index')}}" class="header-table btn btn-outline-success mb-2">Go to user index page</a>
                    {!! Form::open(['method'=>'POST', 'action' => ['AdminUsersController@search'], 'style'=> 'display:inline']) !!}

                        {!! Form::label('search', 'Query:') !!}
                        {!! Form::text('search', null, ['class'=>'form-control', 'style'=> 'display:inline; width:initial', 'required']) !!}

                        {!! Form::submit('search', ['class'=>'btn btn-outline-success mr-2 mb-1']) !!}

                    {!! Form::close() !!} 
                </div>
                <table class="table table-responsive-lg table-striped">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Photo</th>
                        <th scope="col">Name</th>
                        <th scope="col">Gender</th>
                        <th scope="col">Email</th>
                        <th scope="col">Status</th>
                        <th scope="col">Adress</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Created</th>
                        <th scope="col">Updated</th>
                        <th scope="col">process</th>
                    </tr>
                    </thead>
                    <tbody>
                        @if ($users)
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td><img class='img-rounded' height="50" src="{{$user->photo ? url('/') . '/img/private/' . $user->photo->path : url('/') . '/img/private/default.png'}}" alt=""></td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->userGender}}</td>
                                    <td>{{$user->email}}</td>
                                    {!! $user->email_verified_at == NULL ? '<td class="text-danger">Email Not Verified</td>' : '<td class="text-success">Email Verified</td>' !!}
                                    <td>{{$user->address}}</td>
                                    <td>{{$user->phone}}</td>
                                    <td>{{$user->created_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>
                                    <td>{{$user->updated_at->isoFormat(' DD MMM ,ddd Y - HH:mm:ss')}}</td>
                                    <td>
                                        <a href="{{route('admin.users.show', $user->id)}}" class="btn btn-outline-info mr-2 mb-1" >Show Profile</a>
                                        <a   href="{{route('admin.users.edit', $user->id)}}"	class="btn btn-outline-success update mr-2 mb-1">Update</a>
                                        {!! Form::open(['method'=>'DELETE', 'action' => ['AdminUsersController@destroy', $user->id], 'style'=> 'display:inline']) !!}
                                            {!! Form::submit('Delete', ['class'=>'btn btn-outline-danger mr-2 mb-1','onclick'=>"return confirm('Silmek isteğinizden Emin misiniz?')"]) !!}
                                        {!! Form::close() !!} 
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('script')
@endsection